export const DEFAULT_PROMOTION_PIECE = "q" as const;
export const WRONG_MOVE_REVERT_DELAY_MS = 1100;
export const CORRECT_MOVE_HIGHLIGHT_CLEAR_DELAY_MS = 1300;
export const OPPONENT_MOVE_DELAY_MS = 400;
